/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */
import WgtCoupon from './coupon'
import WgtNearbyShop from './nearby-shop'
import WgtCouponCard from './couponcard/index'

// export { default as HeaderHome } from './header-home'
export { default as WgtSlider } from './slider/index'
// export { default as WgtPlateType } from './plate-type'
export { default as WgtLimittimeSlider } from './limittime-slider'

export { default as WgtNavigation } from './navigation'
export { default as WgtGoodsScroll } from './goods-scroll'
export { default as WgtGoodsGrid } from './goods-grid'
export { default as WgtGoodsGridTab } from './goods-grid-tab'
// export { default as WgtShowcase } from './showcase'
export { default as WgtSearchHome } from './search-home'
export { default as WgtFilm } from './film/index'
export { default as WgtWriting } from './writing'
export { default as WgtHeading } from './heading'
export { default as WgtGoods } from './goods/index'
// export { default as WgtGoodsFaverite } from './goods-faverite'
export { default as WgtImgHotZone } from './imghot-zone/index'
export { default as WgtMarquees } from './marquees/index'
export { default as WgtStore } from './store'
export { default as WgtHeadline } from './headline'
// export { default as WgtImgGif } from './img-gif'
export { default as WgtHotTopic } from './hot-topic'
export { default as WgtFloorImg } from './floor-img'
export { default as WgtHomeHeader } from './home-header'
export { default as WgtHomeHeaderShop } from './home-header-shop'
export { default as WgtFullSlider } from './full-slider/index'
export { default as WgtOrderNavigation } from './order-navigation/index'
export { default as WgtShop } from './shop/index'
export { default as WgtStoreAlphabet } from './store-alphabet/index'
export { default as WgtClassify } from './classify/index'
export { default as WgtSpeedkill } from './speedkill/index'
export { default as WgtGroup } from './group/index'
export { default as WgtHotranking } from './hotranking/index'
export { default as WgtLocationModule } from './location-module/index'
export { default as WgtContentPartition } from './content-partition/index'

export { WgtCoupon, WgtNearbyShop, WgtCouponCard }
